trigger:
  branches:
    include:
      - main
  paths:
    include:
      - runbook
pool:
  vmImage: ubuntu-latest

variables:
  serviceprincipal: sp-subconnect-01

stages:
  - stage: release
    displayName: Create runbooks
    jobs:
      - job: create_runbooks
        displayName: Create runbooks
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Create runbooks
            inputs:
              azureSubscription: $(serviceprincipal)
              scriptType: pscore
              scriptPath: runbook/pipeline/deploy.ps1